### ISSUE TITLE
Update styling of newsletter signup at checkout

### ISSUE THREAD

**Issue by pderksen** [sugarcalendar/site#25]
Just enabled the Mailchimp Show Signup at Checkout option  on the live site, then toggled off to make sure it gets the proper styling updates before going live.

The Mailchimp API key and label should be good to go if you want to toggle on and off yourself for testing.

Same as https://github.com/AffiliateWP/theme/issues/199

![image](https://user-images.githubusercontent.com/79667/85790307-e6406500-b6e4-11ea-8e25-d43659fb1a87.png)

**Comment by SDavisMedia** [comment]
@pderksen There was no reason to toggle this back off. There's nothing wrong with that checkbox and label... not enough to warrant turning it off.

**Comment by pderksen** [comment]
Roger. Back on it is!
